### ISSUE TITLE
FYI - I've included this in Webform Validation for Backdrop

### ISSUE THREAD

**Issue by laryn** [twomice/maxlength_webform#2]
Nothing to do on this issue but wanted to say thanks and let you know I've merged this functionality into Webform Validation for Backdrop as a progressive enhancement if MaxLength is enabled:

 - https://github.com/backdrop-contrib/webform_validation/commit/bf8a6bbc6ca0f34c949788066bf45854a37790f7

**Comment by twomice** [comment]
Awesome, thanks @laryn !
